### ISSUE TITLE
python scFAN_predict.py

### ISSUE THREAD

**Issue by Tangke-user** [sperfu/scFAN#3] opened 2021-12-06 13:15 UTC
Hi,
I followed the prediction on single cells instruction using sample files (python3 version). But there was this mistake. Please see the error message below. Could you help me with how I can correct it ? 

python ./python3_codes/scFAN_predict.py -i ./scFAN/Data/LMPP -scindir ./scFAN/Data/new_folder_cisTopics_PBMC_agg -moname LMPP -pb True -oc multiTask_H1hESC_add_ATAC_moreTFs multiTask_GM12878_add_ATAC_moreTFs multiTask_K562_ATAC_more_chipdata

pybedtools.helpers.BEDToolsError:
Command was:

	bedtools intersect -u -sorted -b ./scFAN/tmp_scFAN/pybedtools.tbuv63o5.tmp -a ./scFAN/tmp_scFAN/pybedtools.pyrwfsi4.tmp

Error message was:
ERROR: chromomsome sort ordering for file ./scFAN/tmp_scFAN/pybedtools.tbuv63o5.tmp is inconsistent with other files. Record was:
chrM	0	16571	.	.	.

Thank you!

**Comment by sperfu** [comment] 2021-12-07 07:42
Hi there,

I think the problem is probably due to the sorting issue of using bedtools. Did you use your own data or the provided data. If the bed files are not correctly ordered , then it may cause that problem. Please check https://github.com/arq5x/bedtools/issues/109 for more details.

Thanks,
Laiyi

**Comment by Tangke-user** [comment] 2021-12-13 08:40
Hi Laiyi,

Thank you for your quick reply！I used the provided example data(https://drive.google.com/drive/folders/14rWYM3btpd1qAGKEiQlQ-rOS3LJTQo8b) to run scFAN. Is it possible that you double-check whether the data could be run with the current version scFAN? Or it may be broken with the different versions of pybedtools? Could you specify the package's version used in scFAN?

Also, I found a typo error in [line#338](https://github.com/sperfu/scFAN/blob/master/python3_codes/utils_scFAN.py#L338). It will be good if you could fix the bugs and make the code run fluently. 

Thanks again for this useful tool and it would be wonderful if this could be used widely in future analysis!

Thanks，
Ke

**Comment by sperfu** [comment] 2021-12-18 10:31
Hi Ke,

Thanks for the suggestion, we have double checked the codes especially for the python3 version to make sure it run correctly on that version. All the data we uploaded should be worked fine. We have also uploaded hg19.fa and hg19.fa.flat resource file to the drive, you may download them and put them into the resources folder as well. I think the error you run into is probably due to the resource file conflict, which we have all updated in the current version. Please git clone this scFAN git again to avoid all the potential issues.

As for the package version, we have checked the packages version differences between the python2 and python3. For the users' convenience, we create a git env for users to create their own based on our exact same version. Please make sure to check it out [here](https://github.com/sperfu/scFAN#conda-installationpython3-version). 

As for the typo, thanks for pointing that out. It's now fixed.

Thanks again for the suggestion. 

Best,
Laiyi

**Comment by Tangke-user** [comment] 2021-12-31 02:57
> 

Hi Laiyi,
Thanks for your reply, I'll have a try!

Best,
Ke

**Closed as completed** 2021-12-31 02:57 UTC
